packages:
  - 'docs'
  - 'packages/*'
  - 'tools/*'
allowBuilds:
  '@forge/cli': true
  '@parcel/watcher': true
  '@swc/core': true
  cloudflared: true
  esbuild: true
  keytar: true
  less: true
  nx: true
  unrs-resolver: true
catalog:
  '@commitlint/cli': '^20.2.0'
  '@commitlint/config-angular': '^20.2.0'
  '@eslint/eslintrc': '^2.1.1'
  '@eslint/js': '^9.39.1'
  '@forge/cli': '^13.4.0'
  '@forge/manifest': '^13.3.1'
  '@semantic-release/exec': '^7.1.0'
  '@swc-node/register': '1.11.1'
  '@swc/cli': '0.8.1'
  '@swc/core': '1.15.8'
  '@types/cross-spawn': '6.0.6'
  '@types/fs-extra': '^9.0.13'
  '@types/jest': '30.0.0'
  '@types/js-yaml': '^4.0.5'
  '@types/node': '18.19.21'
  '@typescript-eslint/eslint-plugin': '^8.40.0'
  '@typescript-eslint/parser': '^8.40.0'
  cross-spawn: '7.0.6'
  dotenv: '^16.0.3'
  eslint: '^9.8.0'
  eslint-config-prettier: '10.1.8'
  fs-extra: '^10.1.0'
  graphql: '^16.14.2'
  graphql-request: '^6.1.0'
  husky: '^7.0.4'
  jest: '30.3.0'
  jest-environment-jsdom: '30.0.5'
  jest-environment-node: '30.0.5'
  jest-util: '30.0.5'
  js-yaml: '^4.2.0'
  jsonata: '^2.2.1'
  jsonc-eslint-parser: '^2.4.2'
  prettier: '2.8.0'
  semantic-release: '^25.0.2'
  strip-ansi: '^6.0.1'
  ts-jest: '29.4.6'
  ts-node: '10.9.1'
  tslib: '^2.8.1'
  typescript: '5.9.3'
  typescript-eslint: '^8.62.0'
  verdaccio: '6.7.4'
  vitepress: '^1.1.4'
  webpack: '5.108.0'
  webpack-cli: '^7.0.3'
  webpack-dev-server: '5.2.5'
  zod: '^3.25.76'
catalogs:
  nx:
    '@nx/devkit': '23.0.1'
    '@nx/eslint': '23.0.1'
    '@nx/eslint-plugin': '23.0.1'
    '@nx/jest': '23.0.1'
    '@nx/js': '23.0.1'
    '@nx/node': '23.0.1'
    '@nx/plugin': '23.0.1'
    '@nx/webpack': '23.0.1'
    '@nx/workspace': '23.0.1'
    nx: '23.0.1'
minimumReleaseAgeExclude:
  - webpack@5.108.0
