name: CI
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Checkout [${{ github.ref_name }}]
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v5
        name: Derive appropriate SHAs for base and head for `nx affected` commands
      - uses: ./.github/actions/setup-node-and-pnpm
        with:
          cache: false # Release owns cache writes on release branches.
      - run: pnpm install --frozen-lockfile
      - run: pnpm nx affected --target=build --parallel=2
      - run: pnpm nx affected --target=test --parallel=2
