name: CI
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout [${{ github.ref_name }}]
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
        name: Derive appropriate SHAs for base and head for `nx affected` commands
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npx nx affected --target=build --parallel=2
      - run: npx nx affected --target=test --parallel=2
