name: CI
on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout [${{ github.ref_name }}]
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        name: Derive appropriate SHAs for base and head for `nx affected` commands
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npx nx affected --target=build --parallel=2
      - run: npx nx affected --target=test --parallel=2
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        name: Derive appropriate SHAs for base and head for `nx affected` commands
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: 'Create E2E env file'
        run: |
          echo FORGE_EMAIL=${{ secrets.FORGE_EMAIL }} >> e2e/nx-forge-e2e/.env
          echo FORGE_API_TOKEN=${{ secrets.FORGE_API_TOKEN }} >> e2e/nx-forge-e2e/.env
          echo ATLASSIAN_PRODUCT=${{ vars.ATLASSIAN_PRODUCT }} >> e2e/nx-forge-e2e/.env
          echo ATLASSIAN_SITE_URL=${{ vars.ATLASSIAN_SITE_URL }} >> e2e/nx-forge-e2e/.env
      - run: npm ci
      - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - run: npx nx affected --target=format:check --parallel=2
      - run: npx nx affected --target=lint --parallel=2
      - run: npx nx affected --target=build --parallel=3
      - run: npx nx affected --target=test --parallel=2
      - run: npx nx affected --target=e2e --parallel=2 --no-silent
